import { useEffect, useState } from 'react';
import { Cpu, MemoryStick, HardDrive, Thermometer, ArrowDownUp, Activity as ActivityIcon, Clock, GitBranch, Rocket, ExternalLink, ShieldCheck, Radio } from 'lucide-react';
import type { Snapshot, SystemInfo, Settings, Deployment } from '../../../shared/types';
import { api, bytes, duration, relative } from './api';
import { ActivityList, Chart, Empty, Skeleton, Status } from './components';
export function Metrics({ snapshot, extended = false }: { snapshot: Snapshot; extended?: boolean }) {
  const m = snapshot.metrics;
  if (!m) return <Empty>{snapshot.errors.metrics ?? 'Waiting for host metrics…'}</Empty>;
  const cards = [
    { label: 'CPU usage', value: m.cpu === null ? '—' : m.cpu.toFixed(1), unit: '%', note: `${m.load[0]?.toFixed(2)} load average`, icon: Cpu, metric: 'cpu' as const, color: '#8fcfb5' },
    { label: 'Memory', value: (m.memoryUsed / 1024 ** 3).toFixed(2), unit: 'GB', note: `of ${bytes(m.memoryTotal)} · ${(m.memoryUsed / m.memoryTotal * 100).toFixed(0)}% used`, icon: MemoryStick, metric: 'memoryUsed' as const, color: '#99a9ef' },
    { label: 'CPU temperature', value: m.temperature?.toFixed(1) ?? '—', unit: '°C', note: m.temperature === null ? 'Sensor unavailable' : m.temperature < 80 ? 'Within operating range' : 'Temperature is elevated', icon: Thermometer, metric: 'temperature' as const, color: '#d8ae77' },
    { label: 'Network receive', value: bytes(m.rx), unit: '/s', note: `↑ ${bytes(m.tx)}/s sent`, icon: ArrowDownUp, metric: 'rx' as const, color: '#79b8d5' },
  ];
  return <><div className="metric-grid">{cards.map(card => <section className="metric-card" key={card.label}><div className="metric-label"><span>{card.label}</span><card.icon size={17}/></div><div className="metric-value">{card.value}<span>{card.unit}</span></div><p>{card.note}</p><Chart history={snapshot.history} metric={card.metric} color={card.color}/></section>)}</div>
    <div className="secondary-metrics"><div><HardDrive size={18}/><span>Storage<strong>{bytes(m.diskUsed)} <small>/ {bytes(m.diskTotal)}</small></strong></span><div className="meter"><i style={{ width: `${m.diskTotal ? Math.min(100, (m.diskUsed ?? 0) / m.diskTotal * 100) : 0}%` }}/></div></div><div><ActivityIcon size={18}/><span>System load<strong>{m.load.map(value => value.toFixed(2)).join(' / ')}</strong></span><small>1 / 5 / 15 min</small></div><div><Clock size={18}/><span>Host uptime<strong>{duration(m.uptime)}</strong></span><span className="pulse-dot"/></div></div>
    {extended && <p className="muted tiny">Rolling six-minute history · host samples every 2 seconds · network excludes loopback and Docker bridges</p>}</>;
}
export function DeploymentsPage({ snapshot, deploy }: { snapshot: Snapshot; deploy: (app: Deployment) => void }) {
  const [selected, setSelected] = useState<string | null>(null);
  const current = snapshot.deployments.find(app => app.id === selected);
  return <><div className="section-heading"><div><h2>Applications <span className="count">{snapshot.deployments.length}</span></h2></div></div>
    {!snapshot.deployments.length ? <section className="panel"><Empty>No applications configured. Add an application to config/apps.json and restart the server.</Empty></section> : <div className="deployment-grid">{snapshot.deployments.map(app => <section className="panel deployment-card" key={app.id}><div className="split"><span className="app-icon"><Rocket size={22}/></span><Status value={app.status}/></div><h2>{app.name}</h2><p className="branch"><GitBranch size={14}/>{app.branch}<code>{app.commit ?? 'Unavailable'}</code></p><dl><div><dt>Last deployment</dt><dd title={app.lastDeployment ?? ''}>{relative(app.lastDeployment)}</dd></div><div><dt>Compose project</dt><dd>{app.project}</dd></div><div><dt>Containers</dt><dd>{snapshot.containers.filter(container => container.project === app.project).map(container => container.name).join(', ') || 'None discovered'}</dd></div></dl><div className="split"><button onClick={() => setSelected(app.id)}>View output <ExternalLink size={13}/></button><button className="primary" disabled={snapshot.deployments.some(item => item.status === 'running')} onClick={() => deploy(app)}><Rocket size={14}/>{app.status === 'running' ? 'Deploying…' : 'Deploy'}</button></div></section>)}</div>}
    {current && <section className="panel deployment-output"><div className="panel-heading"><h3>{current.name} · deployment output</h3><Status value={current.status}/></div><pre className="terminal">{current.output.join('') || 'No deployment output yet.'}</pre></section>}
  </>;
}
export function SystemPage({ snapshot }: { snapshot: Snapshot }) {
  const [info, setInfo] = useState<SystemInfo>(); const [error, setError] = useState('');
  useEffect(() => { api<SystemInfo>('/system').then(setInfo).catch(error => setError(error.message)); }, []);
  return <><Metrics snapshot={snapshot} extended/><div className="two-columns"><section className="panel"><div className="panel-heading"><h2>Host information</h2><Cpu size={17}/></div>{error ? <p className="error pad">{error}</p> : !info ? <Skeleton/> : <dl className="details pad">{Object.entries({ Hostname: info.hostname, 'Operating system': info.os, Kernel: info.kernel, Architecture: info.architecture, Processor: info.cpuModel, 'CPU cores': info.cores, 'Docker Engine': info.dockerVersion ?? 'Unavailable' }).map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>}</section>
    <section className="panel"><div className="panel-heading"><h2>Network interfaces</h2><Radio size={17}/></div>{info ? <dl className="details pad">{info.interfaces.map(item => <div key={item.name}><dt>{item.name}</dt><dd>{item.addresses.join(' · ')}</dd></div>)}</dl> : <Empty>Network information unavailable.</Empty>}</section></div></>;
}
export function ActivityPage({ snapshot }: { snapshot: Snapshot }) { const [filter, setFilter] = useState('all'); return <section className="panel"><div className="panel-heading"><h2>Event history <span className="count">{snapshot.activity.length}</span></h2><select aria-label="Filter activity" value={filter} onChange={event => setFilter(event.target.value)}><option value="all">All events</option><option value="container">Containers</option><option value="deployment">Deployments</option><option value="system">System</option></select></div><ActivityList items={snapshot.activity.filter(item => filter === 'all' || item.type.startsWith(filter))}/></section>; }
export function SettingsPage({ cleanup, logout }: { cleanup: () => void; logout: () => void }) {
  const [settings, setSettings] = useState<Settings>(); const [error, setError] = useState('');
  useEffect(() => { api<Settings>('/settings').then(setSettings).catch(error => setError(error.message)); }, []);
  return <div className="settings-layout"><section className="panel"><div className="panel-heading"><h2>Security & configuration</h2><ShieldCheck size={18}/></div><div className="pad"><p className="muted">Configuration is managed on the server. Secret values are never sent to this dashboard.</p>{error && <p className="error">{error}</p>}{settings ? <dl className="details">{Object.entries({ Account: settings.username, 'Public origin': settings.origin, 'Secure cookies': settings.secureCookies ? 'Enabled' : 'Local development only', 'n8n webhook': settings.webhookEnabled ? 'Enabled' : 'Not configured', 'Metrics source': settings.hostMetrics ? 'Read-only host mounts' : 'Local Linux /proc', 'Sample interval': `${settings.sampleSeconds} seconds`, 'Session expiry': '8 hours' }).map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl> : !error && <Skeleton/>}<button onClick={logout}>Sign out of Control Center</button></div></section><section className="panel"><div className="panel-heading"><h2>Maintenance</h2></div><div className="pad"><h3>Clean up dangling images</h3><p className="muted">Remove untagged, unused image layers. Running containers and named images are retained.</p><button onClick={cleanup}>Review image cleanup</button><hr/><h3>Deployment configuration</h3><p className="muted">Edit <code>config/apps.json</code> on the host, then restart the Control Center. Only configured applications can be deployed.</p></div></section></div>;
}
